[build]
  publish = "frontend/dist"
  command = "cd frontend && yarn install && yarn build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
