
INSERT INTO public.translations (key, lang, value) VALUES
-- Transport
('location.airport.title', 'en', 'Pula Airport'),
('location.airport.title', 'hr', 'Zračna luka Pula'),
('location.airport.title', 'it', 'Aeroporto di Pola'),
('location.airport.title', 'de', 'Flughafen Pula'),
('location.airport.distance', 'en', '36 km'),
('location.airport.distance', 'hr', '36 km'),
('location.airport.distance', 'it', '36 km'),
('location.airport.distance', 'de', '36 km'),
('location.airport.description', 'en', 'The main international airport serving Istria with seasonal flights from major European cities.'),
('location.airport.description', 'hr', 'Glavna međunarodna zračna luka koja opslužuje Istru sa sezonskim letovima iz velikih europskih gradova.'),
('location.airport.description', 'it', 'Il principale aeroporto internazionale che serve l''Istria con voli stagionali dalle principali città europee.'),
('location.airport.description', 'de', 'Der wichtigste internationale Flughafen für Istrien mit saisonalen Flügen aus europäischen Großstädten.'),
('location.triesteAirport.title', 'en', 'Trieste Airport'),
('location.triesteAirport.title', 'hr', 'Zračna luka Trst'),
('location.triesteAirport.title', 'it', 'Aeroporto di Trieste'),
('location.triesteAirport.title', 'de', 'Flughafen Triest'),
('location.triesteAirport.distance', 'en', '165 km'),
('location.triesteAirport.distance', 'hr', '165 km'),
('location.triesteAirport.distance', 'it', '165 km'),
('location.triesteAirport.distance', 'de', '165 km'),
('location.triesteAirport.description', 'en', 'Alternative airport in nearby Italy with year-round connections to major destinations.'),
('location.triesteAirport.description', 'hr', 'Alternativna zračna luka u obližnjoj Italiji s cjelogodišnjim vezama prema glavnim odredištima.'),
('location.triesteAirport.description', 'it', 'Aeroporto alternativo nella vicina Italia con collegamenti tutto l''anno verso le principali destinazioni.'),
('location.triesteAirport.description', 'de', 'Alternativer Flughafen im nahen Italien mit ganzjährigen Verbindungen zu wichtigen Zielen.'),
('location.zagrebAirport.title', 'en', 'Zagreb Airport'),
('location.zagrebAirport.title', 'hr', 'Zračna luka Zagreb'),
('location.zagrebAirport.title', 'it', 'Aeroporto di Zagabria'),
('location.zagrebAirport.title', 'de', 'Flughafen Zagreb'),
('location.zagrebAirport.distance', 'en', '241 km'),
('location.zagrebAirport.distance', 'hr', '241 km'),
('location.zagrebAirport.distance', 'it', '241 km'),
('location.zagrebAirport.distance', 'de', '241 km'),
('location.zagrebAirport.description', 'en', 'Croatia''s largest airport with extensive international connections. Scenic 2.5-hour drive to the villa.'),
('location.zagrebAirport.description', 'hr', 'Najveća hrvatska zračna luka s opsežnim međunarodnim vezama. Slikovita 2,5-satna vožnja do vile.'),
('location.zagrebAirport.description', 'it', 'Il più grande aeroporto della Croazia con ampie connessioni internazionali. Viaggio panoramico di 2,5 ore fino alla villa.'),
('location.zagrebAirport.description', 'de', 'Kroatiens größter Flughafen mit umfangreichen internationalen Verbindungen. Malerische 2,5-stündige Fahrt zur Villa.'),
('location.busStation.title', 'en', 'Bus Station Labin'),
('location.busStation.title', 'hr', 'Autobusni kolodvor Labin'),
('location.busStation.title', 'it', 'Stazione autobus Albona'),
('location.busStation.title', 'de', 'Busbahnhof Labin'),
('location.busStation.distance', 'en', '13 km'),
('location.busStation.distance', 'hr', '13 km'),
('location.busStation.distance', 'it', '13 km'),
('location.busStation.distance', 'de', '13 km'),
('location.busStation.description', 'en', 'Regular bus connections to Rijeka, Pula, and other Istrian destinations. Convenient public transport option.'),
('location.busStation.description', 'hr', 'Redovne autobusne veze prema Rijeci, Puli i drugim istarskim destinacijama. Praktična opcija javnog prijevoza.'),
('location.busStation.description', 'it', 'Collegamenti regolari in autobus per Fiume, Pola e altre destinazioni istriane. Comoda opzione di trasporto pubblico.'),
('location.busStation.description', 'de', 'Regelmäßige Busverbindungen nach Rijeka, Pula und andere istrische Ziele. Praktische öffentliche Verkehrsoption.'),
-- Restaurants
('location.martinPescador.title', 'en', 'Martin Pescador'),
('location.martinPescador.title', 'hr', 'Martin Pescador'),
('location.martinPescador.title', 'it', 'Martin Pescador'),
('location.martinPescador.title', 'de', 'Martin Pescador'),
('location.martinPescador.distance', 'en', '2 km'),
('location.martinPescador.distance', 'hr', '2 km'),
('location.martinPescador.distance', 'it', '2 km'),
('location.martinPescador.distance', 'de', '2 km'),
('location.martinPescador.description', 'en', 'Martin Pescador is a renowned seafood restaurant offering fresh Adriatic catches with terrace dining and sea views.'),
('location.martinPescador.description', 'hr', 'Martin Pescador je poznati restoran s plodovima mora koji nudi svježi jadranski ulov uz blagovanje na terasi s pogledom na more.'),
('location.martinPescador.description', 'it', 'Martin Pescador è un rinomato ristorante di pesce che offre pescato fresco dell''Adriatico con terrazza e vista mare.'),
('location.martinPescador.description', 'de', 'Martin Pescador ist ein renommiertes Fischrestaurant mit frischem adriatischem Fang, Terrassenessen und Meerblick.'),
('location.konobaNando.title', 'en', 'Konoba Nando'),
('location.konobaNando.title', 'hr', 'Konoba Nando'),
('location.konobaNando.title', 'it', 'Konoba Nando'),
('location.konobaNando.title', 'de', 'Konoba Nando'),
('location.konobaNando.distance', 'en', '2 km'),
('location.konobaNando.distance', 'hr', '2 km'),
('location.konobaNando.distance', 'it', '2 km'),
('location.konobaNando.distance', 'de', '2 km'),
('location.konobaNando.description', 'en', 'Traditional Istrian tavern serving homemade pasta, truffles, and local wines in a rustic setting.'),
('location.konobaNando.description', 'hr', 'Tradicionalna istarska konoba s domaćom tjesteninom, tartufima i lokalnim vinima u rustikalnom ambijentu.'),
('location.konobaNando.description', 'it', 'Taverna istriana tradizionale con pasta fatta in casa, tartufi e vini locali in ambiente rustico.'),
('location.konobaNando.description', 'de', 'Traditionelle istrische Taverne mit hausgemachter Pasta, Trüffeln und lokalen Weinen in rustikalem Ambiente.'),
('location.pizzeriaRumore.title', 'en', 'Pizzeria Rumore'),
('location.pizzeriaRumore.title', 'hr', 'Pizzeria Rumore'),
('location.pizzeriaRumore.title', 'it', 'Pizzeria Rumore'),
('location.pizzeriaRumore.title', 'de', 'Pizzeria Rumore'),
('location.pizzeriaRumore.distance', 'en', '12 km'),
('location.pizzeriaRumore.distance', 'hr', '12 km'),
('location.pizzeriaRumore.distance', 'it', '12 km'),
('location.pizzeriaRumore.distance', 'de', '12 km'),
('location.pizzeriaRumore.description', 'en', 'This popular Labin pizzeria serves delicious wood-fired pizzas in a lively, family-friendly atmosphere.'),
('location.pizzeriaRumore.description', 'hr', 'Ova popularna labinska pizzeria poslužuje ukusne pizze iz krušne peći u živahnoj obiteljskoj atmosferi.'),
('location.pizzeriaRumore.description', 'it', 'Questa popolare pizzeria di Albona serve deliziose pizze cotte a legna in un''atmosfera vivace e familiare.'),
('location.pizzeriaRumore.description', 'de', 'Diese beliebte Pizzeria in Labin serviert köstliche Holzofenpizzen in einer lebhaften, familienfreundlichen Atmosphäre.'),
('location.stareStaze.title', 'en', 'Stare Staze'),
('location.stareStaze.title', 'hr', 'Stare Staze'),
('location.stareStaze.title', 'it', 'Stare Staze'),
('location.stareStaze.title', 'de', 'Stare Staze'),
('location.stareStaze.distance', 'en', '23 km'),
('location.stareStaze.distance', 'hr', '23 km'),
('location.stareStaze.distance', 'it', '23 km'),
('location.stareStaze.distance', 'de', '23 km'),
('location.stareStaze.description', 'en', 'Award-winning restaurant featuring creative Istrian cuisine with local ingredients and excellent wine pairing.'),
('location.stareStaze.description', 'hr', 'Nagrađivani restoran s kreativnom istarskom kuhinjom, lokalnim namirnicama i izvrsnim uparivanjem vina.'),
('location.stareStaze.description', 'it', 'Ristorante premiato con cucina istriana creativa, ingredienti locali e ottimi abbinamenti di vini.'),
('location.stareStaze.description', 'de', 'Preisgekröntes Restaurant mit kreativer istrischer Küche, lokalen Zutaten und ausgezeichneter Weinbegleitung.'),
-- Supermarkets
('location.spar.title', 'en', 'Špar'),
('location.spar.title', 'hr', 'Špar'),
('location.spar.title', 'it', 'Špar'),
('location.spar.title', 'de', 'Špar'),
('location.spar.distance', 'en', '13 km'),
('location.spar.distance', 'hr', '13 km'),
('location.spar.distance', 'it', '13 km'),
('location.spar.distance', 'de', '13 km'),
('location.spar.description', 'en', 'Full-service supermarket in Labin with fresh produce, bakery, and wide product selection.'),
('location.spar.description', 'hr', 'Supermarket s punom uslugom u Labinu sa svježim proizvodima, pekarnicom i širokim izborom.'),
('location.spar.description', 'it', 'Supermercato completo ad Albona con prodotti freschi, panetteria e ampia selezione.'),
('location.spar.description', 'de', 'Vollsortiment-Supermarkt in Labin mit frischen Produkten, Bäckerei und großer Auswahl.'),
('location.plodine.title', 'en', 'Plodine'),
('location.plodine.title', 'hr', 'Plodine'),
('location.plodine.title', 'it', 'Plodine'),
('location.plodine.title', 'de', 'Plodine'),
('location.plodine.distance', 'en', '12 km'),
('location.plodine.distance', 'hr', '12 km'),
('location.plodine.distance', 'it', '12 km'),
('location.plodine.distance', 'de', '12 km'),
('location.plodine.description', 'en', 'Large Croatian supermarket chain with competitive prices and excellent meat and dairy sections.'),
('location.plodine.description', 'hr', 'Veliki hrvatski lanac supermarketa s konkurentnim cijenama i izvrsnim odjelom mesa i mliječnih proizvoda.'),
('location.plodine.description', 'it', 'Grande catena di supermercati croata con prezzi competitivi e ottimi reparti carne e latticini.'),
('location.plodine.description', 'de', 'Große kroatische Supermarktkette mit günstigen Preisen und ausgezeichneten Fleisch- und Milchabteilungen.'),
('location.lidl.title', 'en', 'Lidl'),
('location.lidl.title', 'hr', 'Lidl'),
('location.lidl.title', 'it', 'Lidl'),
('location.lidl.title', 'de', 'Lidl'),
('location.lidl.distance', 'en', '12 km'),
('location.lidl.distance', 'hr', '12 km'),
('location.lidl.distance', 'it', '12 km'),
('location.lidl.distance', 'de', '12 km'),
('location.lidl.description', 'en', 'European discount supermarket with quality products at affordable prices. Weekly special offers.'),
('location.lidl.description', 'hr', 'Europski diskonti supermarket s kvalitetnim proizvodima po pristupačnim cijenama. Tjedne akcije.'),
('location.lidl.description', 'it', 'Supermercato discount europeo con prodotti di qualità a prezzi accessibili. Offerte settimanali.'),
('location.lidl.description', 'de', 'Europäischer Discounter mit Qualitätsprodukten zu erschwinglichen Preisen. Wöchentliche Sonderangebote.'),
('location.eurospin.title', 'en', 'Eurospin'),
('location.eurospin.title', 'hr', 'Eurospin'),
('location.eurospin.title', 'it', 'Eurospin'),
('location.eurospin.title', 'de', 'Eurospin'),
('location.eurospin.distance', 'en', '15 km'),
('location.eurospin.distance', 'hr', '15 km'),
('location.eurospin.distance', 'it', '15 km'),
('location.eurospin.distance', 'de', '15 km'),
('location.eurospin.description', 'en', 'Italian discount chain known for great value, Italian products, and fresh bakery items.'),
('location.eurospin.description', 'hr', 'Talijanski diskontni lanac poznat po odličnoj vrijednosti, talijanskim proizvodima i svježim pekarskim proizvodima.'),
('location.eurospin.description', 'it', 'Catena discount italiana nota per ottimo rapporto qualità-prezzo, prodotti italiani e panetteria fresca.'),
('location.eurospin.description', 'de', 'Italienische Discount-Kette bekannt für gutes Preis-Leistung, italienische Produkte und frische Backwaren.'),
-- House Rules
('contact.rules.title', 'en', 'House Rules'),
('contact.rules.title', 'hr', 'Kućni red'),
('contact.rules.title', 'it', 'Regole della Casa'),
('contact.rules.title', 'de', 'Hausregeln'),
('contact.rules.noPets', 'en', 'No pets allowed'),
('contact.rules.noPets', 'hr', 'Bez kućnih ljubimaca'),
('contact.rules.noPets', 'it', 'Animali non ammessi'),
('contact.rules.noPets', 'de', 'Keine Haustiere erlaubt'),
('contact.rules.noSmoking', 'en', 'No smoking'),
('contact.rules.noSmoking', 'hr', 'Zabranjeno pušenje'),
('contact.rules.noSmoking', 'it', 'Vietato fumare'),
('contact.rules.noSmoking', 'de', 'Rauchen verboten'),
('contact.rules.maxGuests', 'en', 'Maximum 8 guests'),
('contact.rules.maxGuests', 'hr', 'Maksimalno 8 gostiju'),
('contact.rules.maxGuests', 'it', 'Massimo 8 ospiti'),
('contact.rules.maxGuests', 'de', 'Maximal 8 Gäste'),
('contact.rules.quietHours', 'en', 'Quiet hours: 22:00 – 07:00'),
('contact.rules.quietHours', 'hr', 'Vrijeme tišine: 22:00 – 07:00'),
('contact.rules.quietHours', 'it', 'Ore di silenzio: 22:00 – 07:00'),
('contact.rules.quietHours', 'de', 'Ruhezeiten: 22:00 – 07:00'),
('contact.rules.noParties', 'en', 'No parties or events'),
('contact.rules.noParties', 'hr', 'Zabrane zabave i događaji'),
('contact.rules.noParties', 'it', 'Feste ed eventi vietati'),
('contact.rules.noParties', 'de', 'Keine Partys oder Veranstaltungen'),
-- About times
('about.arrivalTime', 'en', 'Arrival time'),
('about.arrivalTime', 'hr', 'Vrijeme dolaska'),
('about.arrivalTime', 'it', 'Orario di arrivo'),
('about.arrivalTime', 'de', 'Ankunftszeit'),
('about.departureTime', 'en', 'Departure by'),
('about.departureTime', 'hr', 'Odlazak do'),
('about.departureTime', 'it', 'Partenza entro'),
('about.departureTime', 'de', 'Abreise bis'),
('about.arrival', 'en', 'Arrival'),
('about.arrival', 'hr', 'Dolazak'),
('about.arrival', 'it', 'Arrivo'),
('about.arrival', 'de', 'Ankunft'),
('about.departure', 'en', 'Departure by'),
('about.departure', 'hr', 'Odlazak do'),
('about.departure', 'it', 'Partenza entro'),
('about.departure', 'de', 'Abreise bis'),
('contact.host', 'en', 'Host: Vedran Grubišić'),
('contact.host', 'hr', 'Domaćin: Vedran Grubišić'),
('contact.host', 'it', 'Host: Vedran Grubišić'),
('contact.host', 'de', 'Gastgeber: Vedran Grubišić'),
-- About Section
('about.label', 'en', 'About the Villa'),
('about.label', 'hr', 'O Vili'),
('about.label', 'it', 'Sulla Villa'),
('about.label', 'de', 'Über die Villa'),
('about.title', 'en', 'Villa Palazzina Burjaki'),
('about.title', 'hr', 'Villa Palazzina Burjaki'),
('about.title', 'it', 'Villa Palazzina Burjaki'),
('about.title', 'de', 'Villa Palazzina Burjaki'),
('about.subtitle', 'en', 'A 350m² villa with authentic Istrian character, 4 bedrooms, 5 bathrooms, private pool, jacuzzi, sauna, and fitness center in the heart of Istria.'),
('about.subtitle', 'hr', 'Vila od 350m² s autentičnim istarskim karakterom, 4 spavaće sobe, 5 kupaonica, privatni bazen, jacuzzi, sauna i fitness centar u srcu Istre.'),
('about.subtitle', 'it', 'Una villa di 350m² con autentico carattere istriano, 4 camere da letto, 5 bagni, piscina privata, jacuzzi, sauna e centro fitness nel cuore dell''Istria.'),
('about.subtitle', 'de', 'Eine 350m² Villa mit authentischem istrischem Charakter, 4 Schlafzimmern, 5 Badezimmern, privatem Pool, Whirlpool, Sauna und Fitnesscenter im Herzen Istriens.'),
('about.description', 'en', 'Nestled in the peaceful Istrian surroundings of Trgetari, Villa Burjaki offers the perfect blend of privacy, comfort, and authentic Mediterranean ambiance. Surrounded by nature and just a few minutes from the sea, the villa is an ideal choice for guests seeking tranquility while remaining close to the most beautiful beaches of eastern Istria.'),
('about.description', 'hr', 'Smještena u mirnom istarskom okruženju Trgetara, Villa Burjaki nudi savršen spoj privatnosti, udobnosti i autentičnog mediteranskog ugođaja. Okružena prirodom, a svega nekoliko minuta od mora, vila je idealan izbor za goste koji žele mir, ali i blizinu najljepših plaža istočne Istre.'),
('about.description', 'it', 'Immersa nella tranquilla atmosfera istriana di Trgetari, Villa Burjaki offre la perfetta combinazione di privacy, comfort e autentico fascino mediterraneo. Circondata dalla natura e a pochi minuti dal mare, la villa è la scelta ideale per gli ospiti che cercano tranquillità pur rimanendo vicini alle più belle spiagge dell''Istria orientale.'),
('about.description', 'de', 'Eingebettet in die friedliche istrische Umgebung von Trgetari bietet Villa Burjaki die perfekte Mischung aus Privatsphäre, Komfort und authentischem mediterranem Ambiente. Umgeben von Natur und nur wenige Minuten vom Meer entfernt, ist die Villa die ideale Wahl für Gäste, die Ruhe suchen und gleichzeitig in der Nähe der schönsten Strände Ostistriens bleiben möchten.'),
('about.stats.area', 'en', 'Living Area'),
('about.stats.area', 'hr', 'Stambena Površina'),
('about.stats.area', 'it', 'Superficie Abitabile'),
('about.stats.area', 'de', 'Wohnfläche'),
('about.stats.bedrooms', 'en', 'Bedrooms'),
('about.stats.bedrooms', 'hr', 'Spavaće Sobe'),
('about.stats.bedrooms', 'it', 'Camere da Letto'),
('about.stats.bedrooms', 'de', 'Schlafzimmer'),
('about.stats.bathrooms', 'en', 'Bathrooms'),
('about.stats.bathrooms', 'hr', 'Kupaonice'),
('about.stats.bathrooms', 'it', 'Bagni'),
('about.stats.bathrooms', 'de', 'Badezimmer'),
('about.stats.guests', 'en', 'Max Guests'),
('about.stats.guests', 'hr', 'Maks. Gostiju'),
('about.stats.guests', 'it', 'Max Ospiti'),
('about.stats.guests', 'de', 'Max. Gäste'),
('about.checkin', 'en', 'Check-in'),
('about.checkin', 'hr', 'Prijava'),
('about.checkin', 'it', 'Check-in'),
('about.checkin', 'de', 'Check-in'),
('about.checkout', 'en', 'Check-out'),
('about.checkout', 'hr', 'Odjava'),
('about.checkout', 'it', 'Check-out'),
('about.checkout', 'de', 'Check-out'),
('about.rating', 'en', 'Guest Rating'),
('about.rating', 'hr', 'Ocjena Gostiju'),
('about.rating', 'it', 'Valutazione Ospiti'),
('about.rating', 'de', 'Gästebewertung'),
('about.host', 'en', 'Your Host'),
('about.host', 'hr', 'Vaš Domaćin'),
('about.host', 'it', 'Il Tuo Host'),
('about.host', 'de', 'Ihr Gastgeber');
