
-- Insert all privacy.* and cookie.* translation keys for all 4 languages
INSERT INTO public.translations (key, lang, value) VALUES
-- privacy.title
('privacy.title', 'en', 'Privacy Policy'),
('privacy.title', 'hr', 'Politika privatnosti'),
('privacy.title', 'it', 'Informativa sulla privacy'),
('privacy.title', 'de', 'Datenschutzerklärung'),
-- privacy.intro
('privacy.intro', 'en', 'Villa Palazzina Burjaki respects your privacy and is committed to protecting your personal data. This privacy policy explains how we handle information when you visit our website.'),
('privacy.intro', 'hr', 'Villa Palazzina Burjaki poštuje vašu privatnost i predana je zaštiti vaših osobnih podataka. Ova politika privatnosti objašnjava kako postupamo s informacijama kada posjetite našu web stranicu.'),
('privacy.intro', 'it', 'Villa Palazzina Burjaki rispetta la tua privacy e si impegna a proteggere i tuoi dati personali. Questa informativa sulla privacy spiega come gestiamo le informazioni quando visiti il nostro sito web.'),
('privacy.intro', 'de', 'Villa Palazzina Burjaki respektiert Ihre Privatsphäre und verpflichtet sich zum Schutz Ihrer persönlichen Daten. Diese Datenschutzerklärung erklärt, wie wir mit Informationen umgehen, wenn Sie unsere Website besuchen.'),
-- privacy.dataCollection
('privacy.dataCollection.title', 'en', 'Data Collection'),
('privacy.dataCollection.title', 'hr', 'Prikupljanje podataka'),
('privacy.dataCollection.title', 'it', 'Raccolta dati'),
('privacy.dataCollection.title', 'de', 'Datenerfassung'),
('privacy.dataCollection.text', 'en', 'This website may collect the following types of information:'),
('privacy.dataCollection.text', 'hr', 'Ova web stranica može prikupljati sljedeće vrste informacija:'),
('privacy.dataCollection.text', 'it', 'Questo sito web può raccogliere i seguenti tipi di informazioni:'),
('privacy.dataCollection.text', 'de', 'Diese Website kann folgende Arten von Informationen erfassen:'),
('privacy.dataCollection.item1', 'en', 'Contact information you voluntarily provide when contacting us via email'),
('privacy.dataCollection.item1', 'hr', 'Kontakt informacije koje dobrovoljno pružite kada nas kontaktirate putem e-pošte'),
('privacy.dataCollection.item1', 'it', 'Informazioni di contatto che fornisci volontariamente quando ci contatti via email'),
('privacy.dataCollection.item1', 'de', 'Kontaktinformationen, die Sie freiwillig angeben, wenn Sie uns per E-Mail kontaktieren'),
('privacy.dataCollection.item2', 'en', 'Technical data from third-party services (Google Maps) that may use cookies'),
('privacy.dataCollection.item2', 'hr', 'Tehnički podaci iz usluga trećih strana (Google Maps) koje mogu koristiti kolačiće'),
('privacy.dataCollection.item2', 'it', 'Dati tecnici da servizi di terze parti (Google Maps) che potrebbero utilizzare cookie'),
('privacy.dataCollection.item2', 'de', 'Technische Daten von Drittanbieterdiensten (Google Maps), die Cookies verwenden können'),
('privacy.dataCollection.item3', 'en', 'Basic analytics data for website performance monitoring'),
('privacy.dataCollection.item3', 'hr', 'Osnovni analitički podaci za praćenje performansi web stranice'),
('privacy.dataCollection.item3', 'it', 'Dati analitici di base per il monitoraggio delle prestazioni del sito web'),
('privacy.dataCollection.item3', 'de', 'Grundlegende Analysedaten zur Überwachung der Website-Leistung'),
-- privacy.dataStorage
('privacy.dataStorage.title', 'en', 'Data Storage'),
('privacy.dataStorage.title', 'hr', 'Pohrana podataka'),
('privacy.dataStorage.title', 'it', 'Archiviazione dati'),
('privacy.dataStorage.title', 'de', 'Datenspeicherung'),
('privacy.dataStorage.text', 'en', 'This website does not store personal data on its servers. Any data you provide via email is handled through your email provider and ours. We do not maintain databases of visitor information.'),
('privacy.dataStorage.text', 'hr', 'Ova web stranica ne pohranjuje osobne podatke na svojim serverima. Svi podaci koje pružite putem e-pošte obrađuju se putem vašeg i našeg pružatelja e-pošte. Ne održavamo baze podataka informacija o posjetiteljima.'),
('privacy.dataStorage.text', 'it', 'Questo sito web non memorizza dati personali sui propri server. Qualsiasi dato fornito via email viene gestito dal tuo provider email e dal nostro. Non manteniamo database di informazioni sui visitatori.'),
('privacy.dataStorage.text', 'de', 'Diese Website speichert keine persönlichen Daten auf ihren Servern. Alle Daten, die Sie per E-Mail bereitstellen, werden über Ihren und unseren E-Mail-Anbieter verarbeitet. Wir führen keine Datenbanken mit Besucherinformationen.'),
-- privacy.thirdParties
('privacy.thirdParties.title', 'en', 'Third-Party Services'),
('privacy.thirdParties.title', 'hr', 'Usluge trećih strana'),
('privacy.thirdParties.title', 'it', 'Servizi di terze parti'),
('privacy.thirdParties.title', 'de', 'Dienste von Drittanbietern'),
('privacy.thirdParties.text', 'en', 'This website uses the following third-party services that may collect data according to their own privacy policies:'),
('privacy.thirdParties.text', 'hr', 'Ova web stranica koristi sljedeće usluge trećih strana koje mogu prikupljati podatke prema svojim pravilima o privatnosti:'),
('privacy.thirdParties.text', 'it', 'Questo sito web utilizza i seguenti servizi di terze parti che potrebbero raccogliere dati secondo le proprie politiche sulla privacy:'),
('privacy.thirdParties.text', 'de', 'Diese Website nutzt folgende Dienste von Drittanbietern, die Daten gemäß ihren eigenen Datenschutzrichtlinien erfassen können:'),
('privacy.thirdParties.item1', 'en', 'Google Maps - for displaying location information'),
('privacy.thirdParties.item1', 'hr', 'Google Maps - za prikaz informacija o lokaciji'),
('privacy.thirdParties.item1', 'it', 'Google Maps - per visualizzare informazioni sulla posizione'),
('privacy.thirdParties.item1', 'de', 'Google Maps - zur Anzeige von Standortinformationen'),
('privacy.thirdParties.item2', 'en', 'Airbnb - for booking redirects (external platform)'),
('privacy.thirdParties.item2', 'hr', 'Airbnb - za preusmjeravanje rezervacija (vanjska platforma)'),
('privacy.thirdParties.item2', 'it', 'Airbnb - per i reindirizzamenti delle prenotazioni (piattaforma esterna)'),
('privacy.thirdParties.item2', 'de', 'Airbnb - für Buchungsweiterleitungen (externe Plattform)'),
('privacy.thirdParties.item3', 'en', 'YouTube (Google) - for displaying video content. Embedded videos may set third-party cookies in accordance with YouTube''s privacy policy.'),
('privacy.thirdParties.item3', 'hr', 'YouTube (Google) – za prikaz video sadržaja. Ugrađeni videozapisi mogu postavljati kolačiće trećih strana u skladu s pravilima privatnosti YouTubea.'),
('privacy.thirdParties.item3', 'it', 'YouTube (Google) - per la visualizzazione di contenuti video. I video incorporati possono impostare cookie di terze parti in conformità con l''informativa sulla privacy di YouTube.'),
('privacy.thirdParties.item3', 'de', 'YouTube (Google) - zur Anzeige von Videoinhalten. Eingebettete Videos können Cookies von Drittanbietern gemäß den Datenschutzrichtlinien von YouTube setzen.'),
-- privacy.analytics
('privacy.analytics.title', 'en', 'Website Analytics'),
('privacy.analytics.title', 'hr', 'Analitika web stranice'),
('privacy.analytics.title', 'it', 'Analisi del sito web'),
('privacy.analytics.title', 'de', 'Website-Analytik'),
('privacy.analytics.text', 'en', 'This website uses Cloudflare Web Analytics to collect anonymous visitor statistics. This service:'),
('privacy.analytics.text', 'hr', 'Ova web stranica koristi Cloudflare Web Analytics za prikupljanje anonimne statistike posjetitelja. Ova usluga:'),
('privacy.analytics.text', 'it', 'Questo sito web utilizza Cloudflare Web Analytics per raccogliere statistiche anonime sui visitatori. Questo servizio:'),
('privacy.analytics.text', 'de', 'Diese Website verwendet Cloudflare Web Analytics zur Erfassung anonymer Besucherstatistiken. Dieser Dienst:'),
('privacy.analytics.item1', 'en', 'Does not use cookies'),
('privacy.analytics.item1', 'hr', 'Ne koristi kolačiće'),
('privacy.analytics.item1', 'it', 'Non utilizza cookie'),
('privacy.analytics.item1', 'de', 'Verwendet keine Cookies'),
('privacy.analytics.item2', 'en', 'Does not collect personal data'),
('privacy.analytics.item2', 'hr', 'Ne prikuplja osobne podatke'),
('privacy.analytics.item2', 'it', 'Non raccoglie dati personali'),
('privacy.analytics.item2', 'de', 'Erfasst keine persönlichen Daten'),
('privacy.analytics.item3', 'en', 'Is used exclusively for anonymous traffic statistics'),
('privacy.analytics.item3', 'hr', 'Koristi se isključivo za anonimnu statistiku prometa'),
('privacy.analytics.item3', 'it', 'Viene utilizzato esclusivamente per statistiche anonime sul traffico'),
('privacy.analytics.item3', 'de', 'Wird ausschließlich für anonyme Verkehrsstatistiken verwendet'),
-- privacy.gdprRights
('privacy.gdprRights.title', 'en', 'Your Rights Under GDPR'),
('privacy.gdprRights.title', 'hr', 'Vaša prava prema GDPR-u'),
('privacy.gdprRights.title', 'it', 'I tuoi diritti secondo il GDPR'),
('privacy.gdprRights.title', 'de', 'Ihre Rechte nach DSGVO'),
('privacy.gdprRights.text', 'en', 'Under the General Data Protection Regulation (GDPR), you have the following rights:'),
('privacy.gdprRights.text', 'hr', 'Prema Općoj uredbi o zaštiti podataka (GDPR), imate sljedeća prava:'),
('privacy.gdprRights.text', 'it', 'Ai sensi del Regolamento Generale sulla Protezione dei Dati (GDPR), hai i seguenti diritti:'),
('privacy.gdprRights.text', 'de', 'Gemäß der Datenschutz-Grundverordnung (DSGVO) haben Sie folgende Rechte:'),
('privacy.gdprRights.item1', 'en', 'Right of access - to request copies of your personal data'),
('privacy.gdprRights.item1', 'hr', 'Pravo pristupa - zatražiti kopije vaših osobnih podataka'),
('privacy.gdprRights.item1', 'it', 'Diritto di accesso - richiedere copie dei tuoi dati personali'),
('privacy.gdprRights.item1', 'de', 'Auskunftsrecht - Kopien Ihrer persönlichen Daten anzufordern'),
('privacy.gdprRights.item2', 'en', 'Right to rectification - to request correction of inaccurate data'),
('privacy.gdprRights.item2', 'hr', 'Pravo na ispravak - zatražiti ispravak netočnih podataka'),
('privacy.gdprRights.item2', 'it', 'Diritto di rettifica - richiedere la correzione di dati inesatti'),
('privacy.gdprRights.item2', 'de', 'Recht auf Berichtigung - Korrektur unrichtiger Daten zu verlangen'),
('privacy.gdprRights.item3', 'en', 'Right to erasure - to request deletion of your data'),
('privacy.gdprRights.item3', 'hr', 'Pravo na brisanje - zatražiti brisanje vaših podataka'),
('privacy.gdprRights.item3', 'it', 'Diritto alla cancellazione - richiedere la cancellazione dei tuoi dati'),
('privacy.gdprRights.item3', 'de', 'Recht auf Löschung - Löschung Ihrer Daten zu verlangen'),
('privacy.gdprRights.item4', 'en', 'Right to restrict processing - to limit how we use your data'),
('privacy.gdprRights.item4', 'hr', 'Pravo na ograničenje obrade - ograničiti kako koristimo vaše podatke'),
('privacy.gdprRights.item4', 'it', 'Diritto di limitare il trattamento - limitare come utilizziamo i tuoi dati'),
('privacy.gdprRights.item4', 'de', 'Recht auf Einschränkung der Verarbeitung - zu beschränken, wie wir Ihre Daten verwenden'),
('privacy.gdprRights.item5', 'en', 'Right to object - to object to the processing of your data'),
('privacy.gdprRights.item5', 'hr', 'Pravo na prigovor - prigovoriti obradi vaših podataka'),
('privacy.gdprRights.item5', 'it', 'Diritto di opposizione - opporsi al trattamento dei tuoi dati'),
('privacy.gdprRights.item5', 'de', 'Widerspruchsrecht - der Verarbeitung Ihrer Daten zu widersprechen'),
-- privacy.contact
('privacy.contact.title', 'en', 'Contact Us'),
('privacy.contact.title', 'hr', 'Kontaktirajte nas'),
('privacy.contact.title', 'it', 'Contattaci'),
('privacy.contact.title', 'de', 'Kontaktieren Sie uns'),
('privacy.contact.text', 'en', 'If you have any questions about this privacy policy or wish to exercise your rights, please contact us:'),
('privacy.contact.text', 'hr', 'Ako imate pitanja o ovoj politici privatnosti ili želite ostvariti svoja prava, molimo kontaktirajte nas:'),
('privacy.contact.text', 'it', 'Se hai domande su questa informativa sulla privacy o desideri esercitare i tuoi diritti, contattaci:'),
('privacy.contact.text', 'de', 'Wenn Sie Fragen zu dieser Datenschutzerklärung haben oder Ihre Rechte ausüben möchten, kontaktieren Sie uns bitte:'),
('privacy.lastUpdated', 'en', 'Last updated'),
('privacy.lastUpdated', 'hr', 'Posljednje ažuriranje'),
('privacy.lastUpdated', 'it', 'Ultimo aggiornamento'),
('privacy.lastUpdated', 'de', 'Zuletzt aktualisiert'),
-- cookie.title
('cookie.title', 'en', 'Cookie Policy'),
('cookie.title', 'hr', 'Politika kolačića'),
('cookie.title', 'it', 'Politica sui cookie'),
('cookie.title', 'de', 'Cookie-Richtlinie'),
('cookie.intro', 'en', 'This Cookie Policy explains how Villa Palazzina Burjaki uses cookies and similar technologies on this website.'),
('cookie.intro', 'hr', 'Ova politika kolačića objašnjava kako Villa Palazzina Burjaki koristi kolačiće i slične tehnologije na ovoj web stranici.'),
('cookie.intro', 'it', 'Questa politica sui cookie spiega come Villa Palazzina Burjaki utilizza i cookie e tecnologie simili su questo sito web.'),
('cookie.intro', 'de', 'Diese Cookie-Richtlinie erklärt, wie Villa Palazzina Burjaki Cookies und ähnliche Technologien auf dieser Website verwendet.'),
('cookie.whatAreCookies.title', 'en', 'What Are Cookies?'),
('cookie.whatAreCookies.title', 'hr', 'Što su kolačići?'),
('cookie.whatAreCookies.title', 'it', 'Cosa sono i cookie?'),
('cookie.whatAreCookies.title', 'de', 'Was sind Cookies?'),
('cookie.whatAreCookies.text', 'en', 'Cookies are small text files that are stored on your device when you visit a website. They help websites function properly and provide information to website owners.'),
('cookie.whatAreCookies.text', 'hr', 'Kolačići su male tekstualne datoteke koje se pohranjuju na vašem uređaju kada posjetite web stranicu. Pomažu web stranicama da pravilno funkcioniraju i pružaju informacije vlasnicima web stranica.'),
('cookie.whatAreCookies.text', 'it', 'I cookie sono piccoli file di testo che vengono memorizzati sul tuo dispositivo quando visiti un sito web. Aiutano i siti web a funzionare correttamente e forniscono informazioni ai proprietari dei siti.'),
('cookie.whatAreCookies.text', 'de', 'Cookies sind kleine Textdateien, die auf Ihrem Gerät gespeichert werden, wenn Sie eine Website besuchen. Sie helfen Websites, ordnungsgemäß zu funktionieren, und liefern Informationen an Website-Betreiber.'),
('cookie.typesOfCookies.title', 'en', 'Types of Cookies We Use'),
('cookie.typesOfCookies.title', 'hr', 'Vrste kolačića koje koristimo'),
('cookie.typesOfCookies.title', 'it', 'Tipi di cookie che utilizziamo'),
('cookie.typesOfCookies.title', 'de', 'Arten von Cookies, die wir verwenden'),
('cookie.typesOfCookies.text', 'en', 'This website uses minimal cookies:'),
('cookie.typesOfCookies.text', 'hr', 'Ova web stranica koristi minimalne kolačiće:'),
('cookie.typesOfCookies.text', 'it', 'Questo sito web utilizza cookie minimi:'),
('cookie.typesOfCookies.text', 'de', 'Diese Website verwendet minimale Cookies:'),
('cookie.typesOfCookies.essential.title', 'en', 'Essential Cookies'),
('cookie.typesOfCookies.essential.title', 'hr', 'Osnovni kolačići'),
('cookie.typesOfCookies.essential.title', 'it', 'Cookie essenziali'),
('cookie.typesOfCookies.essential.title', 'de', 'Wesentliche Cookies'),
('cookie.typesOfCookies.essential.text', 'en', 'These cookies are necessary for the website to function properly. They include language preference storage.'),
('cookie.typesOfCookies.essential.text', 'hr', 'Ovi kolačići su neophodni za pravilno funkcioniranje web stranice. Uključuju pohranu postavki jezika.'),
('cookie.typesOfCookies.essential.text', 'it', 'Questi cookie sono necessari per il corretto funzionamento del sito web. Includono la memorizzazione delle preferenze linguistiche.'),
('cookie.typesOfCookies.essential.text', 'de', 'Diese Cookies sind für das ordnungsgemäße Funktionieren der Website erforderlich. Sie umfassen die Speicherung von Spracheinstellungen.'),
('cookie.typesOfCookies.thirdParty.title', 'en', 'Third-Party Cookies'),
('cookie.typesOfCookies.thirdParty.title', 'hr', 'Kolačići trećih strana'),
('cookie.typesOfCookies.thirdParty.title', 'it', 'Cookie di terze parti'),
('cookie.typesOfCookies.thirdParty.title', 'de', 'Cookies von Drittanbietern'),
('cookie.typesOfCookies.thirdParty.text', 'en', 'Some third-party services embedded on this site (such as Google Maps) may set their own cookies according to their privacy policies.'),
('cookie.typesOfCookies.thirdParty.text', 'hr', 'Neke usluge trećih strana ugrađene na ovu stranicu (kao što je Google Maps) mogu postaviti vlastite kolačiće prema svojim pravilima o privatnosti.'),
('cookie.typesOfCookies.thirdParty.text', 'it', 'Alcuni servizi di terze parti incorporati in questo sito (come Google Maps) potrebbero impostare i propri cookie secondo le loro politiche sulla privacy.'),
('cookie.typesOfCookies.thirdParty.text', 'de', 'Einige auf dieser Website eingebettete Drittanbieterdienste (wie Google Maps) können gemäß ihren Datenschutzrichtlinien eigene Cookies setzen.'),
('cookie.thirdPartyServices.title', 'en', 'Third-Party Services'),
('cookie.thirdPartyServices.title', 'hr', 'Usluge trećih strana'),
('cookie.thirdPartyServices.title', 'it', 'Servizi di terze parti'),
('cookie.thirdPartyServices.title', 'de', 'Dienste von Drittanbietern'),
('cookie.thirdPartyServices.text', 'en', 'This website may include content from the following third-party services:'),
('cookie.thirdPartyServices.text', 'hr', 'Ova web stranica može uključivati sadržaj sljedećih usluga trećih strana:'),
('cookie.thirdPartyServices.text', 'it', 'Questo sito web può includere contenuti dei seguenti servizi di terze parti:'),
('cookie.thirdPartyServices.text', 'de', 'Diese Website kann Inhalte folgender Drittanbieterdienste enthalten:'),
('cookie.thirdPartyServices.item1', 'en', 'Google Maps - for interactive map display'),
('cookie.thirdPartyServices.item1', 'hr', 'Google Maps - za interaktivni prikaz karte'),
('cookie.thirdPartyServices.item1', 'it', 'Google Maps - per la visualizzazione di mappe interattive'),
('cookie.thirdPartyServices.item1', 'de', 'Google Maps - für interaktive Kartenanzeige'),
('cookie.thirdPartyServices.item2', 'en', 'Airbnb - for booking platform integration (external link)'),
('cookie.thirdPartyServices.item2', 'hr', 'Airbnb - za integraciju platforme za rezervacije (vanjska veza)'),
('cookie.thirdPartyServices.item2', 'it', 'Airbnb - per l''integrazione della piattaforma di prenotazione (link esterno)'),
('cookie.thirdPartyServices.item2', 'de', 'Airbnb - für Buchungsplattform-Integration (externer Link)'),
('cookie.thirdPartyServices.item3', 'en', 'YouTube (Google) - for embedded video content'),
('cookie.thirdPartyServices.item3', 'hr', 'YouTube (Google) - za ugrađeni video sadržaj'),
('cookie.thirdPartyServices.item3', 'it', 'YouTube (Google) - per contenuti video incorporati'),
('cookie.thirdPartyServices.item3', 'de', 'YouTube (Google) - für eingebettete Videoinhalte'),
('cookie.youtube.title', 'en', 'YouTube Embedded Videos'),
('cookie.youtube.title', 'hr', 'Ugrađeni YouTube videozapisi'),
('cookie.youtube.title', 'it', 'Video YouTube incorporati'),
('cookie.youtube.title', 'de', 'Eingebettete YouTube-Videos'),
('cookie.youtube.text', 'en', 'This website uses embedded YouTube videos to display video content of Villa Palazzina Burjaki. When you play a YouTube video, YouTube (operated by Google) may set cookies and collect data according to their privacy policy.'),
('cookie.youtube.text', 'hr', 'Ova web stranica koristi ugrađene YouTube videozapise za prikaz video sadržaja Ville Palazzina Burjaki. Kada pokrenete YouTube video, YouTube (kojim upravlja Google) može postaviti kolačiće i prikupljati podatke prema svojim pravilima o privatnosti.'),
('cookie.youtube.text', 'it', 'Questo sito web utilizza video YouTube incorporati per visualizzare contenuti video di Villa Palazzina Burjaki. Quando riproduci un video YouTube, YouTube (gestito da Google) potrebbe impostare cookie e raccogliere dati secondo la propria informativa sulla privacy.'),
('cookie.youtube.text', 'de', 'Diese Website verwendet eingebettete YouTube-Videos zur Anzeige von Videoinhalten der Villa Palazzina Burjaki. Wenn Sie ein YouTube-Video abspielen, kann YouTube (betrieben von Google) Cookies setzen und Daten gemäß ihrer Datenschutzrichtlinie erfassen.'),
('cookie.youtube.noControl', 'en', 'The website owner has no control over the data collected by YouTube/Google. For more information about how YouTube handles your data, please refer to:'),
('cookie.youtube.noControl', 'hr', 'Vlasnik web stranice nema kontrolu nad podacima koje prikuplja YouTube/Google. Za više informacija o tome kako YouTube obrađuje vaše podatke, molimo pogledajte:'),
('cookie.youtube.noControl', 'it', 'Il proprietario del sito web non ha alcun controllo sui dati raccolti da YouTube/Google. Per ulteriori informazioni su come YouTube gestisce i tuoi dati, consulta:'),
('cookie.youtube.noControl', 'de', 'Der Website-Betreiber hat keine Kontrolle über die von YouTube/Google erfassten Daten. Weitere Informationen darüber, wie YouTube Ihre Daten verarbeitet, finden Sie unter:'),
('cookie.youtube.googlePrivacy', 'en', 'Google Privacy Policy'),
('cookie.youtube.googlePrivacy', 'hr', 'Google pravila o privatnosti'),
('cookie.youtube.googlePrivacy', 'it', 'Informativa sulla privacy di Google'),
('cookie.youtube.googlePrivacy', 'de', 'Google Datenschutzerklärung'),
('cookie.youtube.youtubeTerms', 'en', 'YouTube Terms of Service'),
('cookie.youtube.youtubeTerms', 'hr', 'YouTube uvjeti korištenja'),
('cookie.youtube.youtubeTerms', 'it', 'Termini di servizio di YouTube'),
('cookie.youtube.youtubeTerms', 'de', 'YouTube Nutzungsbedingungen'),
('cookie.consent.title', 'en', 'Your Consent'),
('cookie.consent.title', 'hr', 'Vaš pristanak'),
('cookie.consent.title', 'it', 'Il tuo consenso'),
('cookie.consent.title', 'de', 'Ihre Einwilligung'),
('cookie.consent.text', 'en', 'By using this website, you consent to the use of cookies as described in this policy. You can manage your cookie preferences through your browser settings.'),
('cookie.consent.text', 'hr', 'Korištenjem ove web stranice pristajete na korištenje kolačića kako je opisano u ovoj politici. Možete upravljati postavkama kolačića putem postavki preglednika.'),
('cookie.consent.text', 'it', 'Utilizzando questo sito web, acconsenti all''uso dei cookie come descritto in questa politica. Puoi gestire le tue preferenze sui cookie attraverso le impostazioni del browser.'),
('cookie.consent.text', 'de', 'Durch die Nutzung dieser Website stimmen Sie der Verwendung von Cookies wie in dieser Richtlinie beschrieben zu. Sie können Ihre Cookie-Einstellungen über Ihre Browsereinstellungen verwalten.'),
('cookie.managing.title', 'en', 'Managing Cookies'),
('cookie.managing.title', 'hr', 'Upravljanje kolačićima'),
('cookie.managing.title', 'it', 'Gestione dei cookie'),
('cookie.managing.title', 'de', 'Cookies verwalten'),
('cookie.managing.text', 'en', 'Most web browsers allow you to control cookies through their settings. You can delete existing cookies, allow or block all cookies, and set preferences for certain websites. Please note that blocking some cookies may affect your experience on this website.'),
('cookie.managing.text', 'hr', 'Većina web preglednika omogućuje upravljanje kolačićima putem svojih postavki. Možete izbrisati postojeće kolačiće, dopustiti ili blokirati sve kolačiće i postaviti postavke za određene web stranice. Imajte na umu da blokiranje nekih kolačića može utjecati na vaše iskustvo na ovoj web stranici.'),
('cookie.managing.text', 'it', 'La maggior parte dei browser web consente di controllare i cookie attraverso le loro impostazioni. Puoi eliminare i cookie esistenti, consentire o bloccare tutti i cookie e impostare preferenze per determinati siti web. Tieni presente che il blocco di alcuni cookie potrebbe influire sulla tua esperienza su questo sito web.'),
('cookie.managing.text', 'de', 'Die meisten Webbrowser ermöglichen es Ihnen, Cookies über ihre Einstellungen zu kontrollieren. Sie können vorhandene Cookies löschen, alle Cookies zulassen oder blockieren und Einstellungen für bestimmte Websites festlegen. Bitte beachten Sie, dass das Blockieren einiger Cookies Ihre Erfahrung auf dieser Website beeinträchtigen kann.'),
('cookie.contact.title', 'en', 'Contact Us'),
('cookie.contact.title', 'hr', 'Kontaktirajte nas'),
('cookie.contact.title', 'it', 'Contattaci'),
('cookie.contact.title', 'de', 'Kontaktieren Sie uns'),
('cookie.contact.text', 'en', 'If you have any questions about our cookie policy, please contact us:'),
('cookie.contact.text', 'hr', 'Ako imate pitanja o našoj politici kolačića, molimo kontaktirajte nas:'),
('cookie.contact.text', 'it', 'Se hai domande sulla nostra politica sui cookie, contattaci:'),
('cookie.contact.text', 'de', 'Wenn Sie Fragen zu unserer Cookie-Richtlinie haben, kontaktieren Sie uns bitte:'),
('cookie.lastUpdated', 'en', 'Last updated'),
('cookie.lastUpdated', 'hr', 'Posljednje ažuriranje'),
('cookie.lastUpdated', 'it', 'Ultimo aggiornamento'),
('cookie.lastUpdated', 'de', 'Zuletzt aktualisiert');
