
INSERT INTO public.translations (key, lang, value) VALUES
-- Navigation
('nav.gallery', 'en', 'Gallery'),
('nav.gallery', 'hr', 'Galerija'),
('nav.gallery', 'it', 'Galleria'),
('nav.gallery', 'de', 'Galerie'),
('nav.amenities', 'en', 'Amenities'),
('nav.amenities', 'hr', 'Sadržaji'),
('nav.amenities', 'it', 'Servizi'),
('nav.amenities', 'de', 'Ausstattung'),
('nav.location', 'en', 'Location'),
('nav.location', 'hr', 'Lokacija'),
('nav.location', 'it', 'Posizione'),
('nav.location', 'de', 'Lage'),
('nav.contact', 'en', 'About'),
('nav.contact', 'hr', 'O nama'),
('nav.contact', 'it', 'Chi siamo'),
('nav.contact', 'de', 'Über uns'),
('nav.bookNow', 'en', 'Book Now'),
('nav.bookNow', 'hr', 'Rezerviraj'),
('nav.bookNow', 'it', 'Prenota'),
('nav.bookNow', 'de', 'Buchen'),
-- Hero
('hero.reserveNow', 'en', 'Book Now'),
('hero.reserveNow', 'hr', 'Rezerviraj'),
('hero.reserveNow', 'it', 'Prenota'),
('hero.reserveNow', 'de', 'Buchen'),
('hero.externalBookingNotice', 'en', 'Redirects to Airbnb · Their terms apply'),
('hero.externalBookingNotice', 'hr', 'Preusmjerava na Airbnb · Vrijede njihovi uvjeti'),
('hero.externalBookingNotice', 'it', 'Reindirizza a Airbnb · Si applicano i loro termini'),
('hero.externalBookingNotice', 'de', 'Weiterleitung zu Airbnb · Es gelten deren Bedingungen'),
('hero.brand', 'en', 'Villa Palazzina Burjaki'),
('hero.brand', 'hr', 'Villa Palazzina Burjaki'),
('hero.brand', 'it', 'Villa Palazzina Burjaki'),
('hero.brand', 'de', 'Villa Palazzina Burjaki'),
('hero.title', 'en', 'Authentic Istrian Escape'),
('hero.title', 'hr', 'Autentični Istarski Bijeg'),
('hero.title', 'it', 'Rifugio Autentico in Istria'),
('hero.title', 'de', 'Authentisches Istrisches Refugium'),
('hero.watchVideo', 'en', 'Watch Video Tour'),
('hero.watchVideo', 'hr', 'Pogledaj Video Turu'),
('hero.watchVideo', 'it', 'Guarda il Video Tour'),
('hero.watchVideo', 'de', 'Video-Tour ansehen'),
('hero.subtitle', 'en', 'Private pool, jacuzzi, sauna & gym. Perfect for families and groups up to 8 guests.'),
('hero.subtitle', 'hr', 'Privatni bazen, jacuzzi, sauna i teretana. Idealno za obitelji i grupe do 8 gostiju.'),
('hero.subtitle', 'it', 'Piscina privata, jacuzzi, sauna e palestra. Perfetta per famiglie e gruppi fino a 8 ospiti.'),
('hero.subtitle', 'de', 'Privatpool, Whirlpool, Sauna & Fitnessraum. Ideal für Familien und Gruppen bis 8 Gäste.'),
('hero.airbnbNote', 'en', 'Reservations exclusively via Airbnb'),
('hero.airbnbNote', 'hr', 'Rezervacije isključivo putem Airbnb-a'),
('hero.airbnbNote', 'it', 'Prenotazioni esclusivamente tramite Airbnb'),
('hero.airbnbNote', 'de', 'Reservierungen ausschließlich über Airbnb'),
-- Booking
('booking.checkIn', 'en', 'Check-in'),
('booking.checkIn', 'hr', 'Dolazak'),
('booking.checkIn', 'it', 'Arrivo'),
('booking.checkIn', 'de', 'Anreise'),
('booking.checkOut', 'en', 'Check-out'),
('booking.checkOut', 'hr', 'Odlazak'),
('booking.checkOut', 'it', 'Partenza'),
('booking.checkOut', 'de', 'Abreise'),
('booking.guests', 'en', 'Guests'),
('booking.guests', 'hr', 'Gosti'),
('booking.guests', 'it', 'Ospiti'),
('booking.guests', 'de', 'Gäste'),
('booking.checkAvailability', 'en', 'Check Availability'),
('booking.checkAvailability', 'hr', 'Provjeri Dostupnost'),
('booking.checkAvailability', 'it', 'Verifica Disponibilità'),
('booking.checkAvailability', 'de', 'Verfügbarkeit Prüfen'),
-- Gallery main
('gallery.label', 'en', 'Interior Design'),
('gallery.label', 'hr', 'Dizajn Interijera'),
('gallery.label', 'it', 'Design d''Interni'),
('gallery.label', 'de', 'Innenarchitektur'),
('gallery.title', 'en', 'Curated Living Spaces'),
('gallery.title', 'hr', 'Pažljivo Uređeni Prostori'),
('gallery.title', 'it', 'Spazi Abitativi Curati'),
('gallery.title', 'de', 'Kuratierte Wohnräume'),
('gallery.subtitle', 'en', 'Where comfort meets sophistication'),
('gallery.subtitle', 'hr', 'Gdje se udobnost susreće s profinjenošću'),
('gallery.subtitle', 'it', 'Dove il comfort incontra la raffinatezza'),
('gallery.subtitle', 'de', 'Wo Komfort auf Raffinesse trifft'),
('gallery.description', 'en', 'Each room has been thoughtfully designed to blend authentic Istrian charm with modern amenities, creating spaces that inspire relaxation and connection.'),
('gallery.description', 'hr', 'Svaka soba je pažljivo dizajnirana kako bi spojila autentični istarski šarm s modernim sadržajima, stvarajući prostore koji inspiriraju opuštanje i povezanost.'),
('gallery.description', 'it', 'Ogni stanza è stata progettata con cura per unire l''autentico fascino istriano con i comfort moderni, creando spazi che ispirano relax e connessione.'),
('gallery.description', 'de', 'Jeder Raum wurde sorgfältig gestaltet, um authentischen istrischen Charme mit modernen Annehmlichkeiten zu verbinden und Räume zu schaffen, die zur Entspannung und Verbundenheit inspirieren.'),
('gallery.feature.spacious', 'en', 'Spacious Rooms'),
('gallery.feature.spacious', 'hr', 'Prostrane Sobe'),
('gallery.feature.spacious', 'it', 'Camere Spaziose'),
('gallery.feature.spacious', 'de', 'Geräumige Zimmer'),
('gallery.feature.authentic', 'en', 'Authentic Design'),
('gallery.feature.authentic', 'hr', 'Autentičan Dizajn'),
('gallery.feature.authentic', 'it', 'Design Autentico'),
('gallery.feature.authentic', 'de', 'Authentisches Design'),
('gallery.feature.natural', 'en', 'Natural Light'),
('gallery.feature.natural', 'hr', 'Prirodno Svjetlo'),
('gallery.feature.natural', 'it', 'Luce Naturale'),
('gallery.feature.natural', 'de', 'Natürliches Licht'),
-- Gallery categories
('gallery.category.all', 'en', 'All'),
('gallery.category.all', 'hr', 'Sve'),
('gallery.category.all', 'it', 'Tutto'),
('gallery.category.all', 'de', 'Alle'),
('gallery.category.exterior', 'en', 'Exterior'),
('gallery.category.exterior', 'hr', 'Eksterijer'),
('gallery.category.exterior', 'it', 'Esterno'),
('gallery.category.exterior', 'de', 'Außenbereich'),
('gallery.category.living', 'en', 'Living Spaces'),
('gallery.category.living', 'hr', 'Dnevni prostori'),
('gallery.category.living', 'it', 'Spazi abitativi'),
('gallery.category.living', 'de', 'Wohnbereiche'),
('gallery.category.bedrooms', 'en', 'Bedrooms'),
('gallery.category.bedrooms', 'hr', 'Spavaće sobe'),
('gallery.category.bedrooms', 'it', 'Camere da letto'),
('gallery.category.bedrooms', 'de', 'Schlafzimmer'),
('gallery.category.bathrooms', 'en', 'Bathrooms'),
('gallery.category.bathrooms', 'hr', 'Kupaonice'),
('gallery.category.bathrooms', 'it', 'Bagni'),
('gallery.category.bathrooms', 'de', 'Badezimmer'),
-- Gallery albums
('gallery.album.pool', 'en', 'Pool & Surroundings'),
('gallery.album.pool', 'hr', 'Bazen & Okoliš'),
('gallery.album.pool', 'it', 'Piscina e dintorni'),
('gallery.album.pool', 'de', 'Pool & Umgebung'),
('gallery.album.terrace', 'en', 'Terrace'),
('gallery.album.terrace', 'hr', 'Terasa'),
('gallery.album.terrace', 'it', 'Terrazza'),
('gallery.album.terrace', 'de', 'Terrasse'),
('gallery.album.backyard', 'en', 'Backyard'),
('gallery.album.backyard', 'hr', 'Stražnje dvorište'),
('gallery.album.backyard', 'it', 'Cortile'),
('gallery.album.backyard', 'de', 'Hinterhof'),
('gallery.album.living', 'en', 'Living Room'),
('gallery.album.living', 'hr', 'Dnevni boravak'),
('gallery.album.living', 'it', 'Soggiorno'),
('gallery.album.living', 'de', 'Wohnzimmer'),
('gallery.album.dining', 'en', 'Dining Room'),
('gallery.album.dining', 'hr', 'Blagovaonica'),
('gallery.album.dining', 'it', 'Sala da pranzo'),
('gallery.album.dining', 'de', 'Esszimmer'),
('gallery.album.kitchen', 'en', 'Kitchen'),
('gallery.album.kitchen', 'hr', 'Kuhinja'),
('gallery.album.kitchen', 'it', 'Cucina'),
('gallery.album.kitchen', 'de', 'Küche'),
('gallery.album.gymSpa', 'en', 'Gym & Spa'),
('gallery.album.gymSpa', 'hr', 'Gym & Spa'),
('gallery.album.gymSpa', 'it', 'Palestra & Spa'),
('gallery.album.gymSpa', 'de', 'Fitness & Spa'),
('gallery.album.laundry', 'en', 'Laundry Room'),
('gallery.album.laundry', 'hr', 'Vešeraj'),
('gallery.album.laundry', 'it', 'Lavanderia'),
('gallery.album.laundry', 'de', 'Waschküche'),
('gallery.album.bedroom', 'en', 'Bedroom'),
('gallery.album.bedroom', 'hr', 'Spavaća soba'),
('gallery.album.bedroom', 'it', 'Camera da letto'),
('gallery.album.bedroom', 'de', 'Schlafzimmer'),
('gallery.album.bedroom1', 'en', 'Ground Floor Bedroom'),
('gallery.album.bedroom1', 'hr', 'Spavaća soba u prizemlju'),
('gallery.album.bedroom1', 'it', 'Camera da letto al piano terra'),
('gallery.album.bedroom1', 'de', 'Schlafzimmer im Erdgeschoss'),
('gallery.album.bedroom2', 'en', 'Bunk Bed Bedroom'),
('gallery.album.bedroom2', 'hr', 'Spavaća soba s krevetima na kat'),
('gallery.album.bedroom2', 'it', 'Camera con letti a castello'),
('gallery.album.bedroom2', 'de', 'Schlafzimmer mit Etagenbetten'),
('gallery.album.bedroom3', 'en', 'Guest Bedroom'),
('gallery.album.bedroom3', 'hr', 'Gostinjska spavaća soba'),
('gallery.album.bedroom3', 'it', 'Camera degli ospiti'),
('gallery.album.bedroom3', 'de', 'Gästezimmer'),
('gallery.album.bedroom4', 'en', 'Master Bedroom'),
('gallery.album.bedroom4', 'hr', 'Glavna spavaća soba'),
('gallery.album.bedroom4', 'it', 'Camera da letto principale'),
('gallery.album.bedroom4', 'de', 'Hauptschlafzimmer'),
('gallery.album.bathroom', 'en', 'Bathroom'),
('gallery.album.bathroom', 'hr', 'Kupaonica'),
('gallery.album.bathroom', 'it', 'Bagno'),
('gallery.album.bathroom', 'de', 'Badezimmer'),
('gallery.album.bathroom1', 'en', 'Ground Floor Bathroom'),
('gallery.album.bathroom1', 'hr', 'Kupaonica u prizemlju'),
('gallery.album.bathroom1', 'it', 'Bagno al piano terra'),
('gallery.album.bathroom1', 'de', 'Badezimmer im Erdgeschoss'),
('gallery.album.bathroom2', 'en', 'Pool Bathroom'),
('gallery.album.bathroom2', 'hr', 'Kupaonica uz bazen'),
('gallery.album.bathroom2', 'it', 'Bagno piscina'),
('gallery.album.bathroom2', 'de', 'Pool-Badezimmer'),
('gallery.album.bathroom3', 'en', 'Guest Bathroom'),
('gallery.album.bathroom3', 'hr', 'Gostinjska kupaonica'),
('gallery.album.bathroom3', 'it', 'Bagno ospiti'),
('gallery.album.bathroom3', 'de', 'Gästebad'),
('gallery.album.bathroom4', 'en', 'Master Bathroom'),
('gallery.album.bathroom4', 'hr', 'Glavna kupaonica'),
('gallery.album.bathroom4', 'it', 'Bagno principale'),
('gallery.album.bathroom4', 'de', 'Hauptbadezimmer'),
('gallery.album.bathroom5', 'en', 'Upstairs Bathroom'),
('gallery.album.bathroom5', 'hr', 'Kupaonica na katu'),
('gallery.album.bathroom5', 'it', 'Bagno al piano superiore'),
('gallery.album.bathroom5', 'de', 'Badezimmer im Obergeschoss'),
-- Gallery video & misc
('gallery.video.title', 'en', 'Video Tour'),
('gallery.video.title', 'hr', 'Video tura'),
('gallery.video.title', 'it', 'Video tour'),
('gallery.video.title', 'de', 'Video-Tour'),
('gallery.video.subtitle', 'en', 'Virtual villa walkthrough'),
('gallery.video.subtitle', 'hr', 'Virtualna šetnja vilom'),
('gallery.video.subtitle', 'it', 'Passeggiata virtuale nella villa'),
('gallery.video.subtitle', 'de', 'Virtueller Villenrundgang'),
('gallery.photos', 'en', 'photos'),
('gallery.photos', 'hr', 'slika'),
('gallery.photos', 'it', 'foto'),
('gallery.photos', 'de', 'Fotos'),
('gallery.photo', 'en', 'photo'),
('gallery.photo', 'hr', 'slika'),
('gallery.photo', 'it', 'foto'),
('gallery.photo', 'de', 'Foto');
