project_id = "vtqeoixvlofguiqvdoyb"

[functions.db-keep-alive]
verify_jwt = false

[functions.translations]
verify_jwt = false

[functions.amenities]
verify_jwt = false

[functions.locations]
verify_jwt = false

[functions.gallery]
verify_jwt = false

[functions.villa-info]
verify_jwt = false
