
INSERT INTO public.translations (key, lang, value) VALUES
-- FAQ
('faq.title', 'en', 'Frequently Asked Questions'),
('faq.title', 'hr', 'Najčešća pitanja gostiju'),
('faq.title', 'it', 'Domande frequenti degli ospiti'),
('faq.title', 'de', 'Häufig gestellte Fragen'),
('faq.pool.question', 'en', 'Is the pool private?'),
('faq.pool.question', 'hr', 'Je li bazen privatan?'),
('faq.pool.question', 'it', 'La piscina è privata?'),
('faq.pool.question', 'de', 'Ist der Pool privat?'),
('faq.pool.answer', 'en', 'Yes, the pool is completely private and exclusively for villa guests.'),
('faq.pool.answer', 'hr', 'Da, bazen je u potpunosti privatan i namijenjen isključivo gostima vile.'),
('faq.pool.answer', 'it', 'Sì, la piscina è completamente privata e riservata esclusivamente agli ospiti della villa.'),
('faq.pool.answer', 'de', 'Ja, der Pool ist vollständig privat und ausschließlich für Villengäste bestimmt.'),
('faq.kitchen.question', 'en', 'Is the kitchen fully equipped?'),
('faq.kitchen.question', 'hr', 'Je li kuhinja potpuno opremljena?'),
('faq.kitchen.question', 'it', 'La cucina è completamente attrezzata?'),
('faq.kitchen.question', 'de', 'Ist die Küche voll ausgestattet?'),
('faq.kitchen.answer', 'en', 'Yes, the kitchen is fully equipped for everyday meal preparation.'),
('faq.kitchen.answer', 'hr', 'Da, kuhinja je u potpunosti opremljena za svakodnevnu pripremu obroka.'),
('faq.kitchen.answer', 'it', 'Sì, la cucina è completamente attrezzata per la preparazione quotidiana dei pasti.'),
('faq.kitchen.answer', 'de', 'Ja, die Küche ist vollständig für die tägliche Zubereitung von Mahlzeiten ausgestattet.'),
('faq.towels.question', 'en', 'Are towels and bed linen included?'),
('faq.towels.question', 'hr', 'Jesu li ručnici i posteljina uključeni?'),
('faq.towels.question', 'it', 'Asciugamani e biancheria da letto sono inclusi?'),
('faq.towels.question', 'de', 'Sind Handtücher und Bettwäsche inklusive?'),
('faq.towels.answer', 'en', 'Yes, guests are provided with towels and bed linen for the entire stay.'),
('faq.towels.answer', 'hr', 'Da, gostima su osigurani ručnici i posteljina za cijeli boravak.'),
('faq.towels.answer', 'it', 'Sì, gli ospiti ricevono asciugamani e biancheria da letto per tutto il soggiorno.'),
('faq.towels.answer', 'de', 'Ja, den Gästen werden Handtücher und Bettwäsche für den gesamten Aufenthalt zur Verfügung gestellt.'),
-- Contact
('contact.title', 'en', 'Get in Touch'),
('contact.title', 'hr', 'Kontaktirajte Nas'),
('contact.title', 'it', 'Contattaci'),
('contact.title', 'de', 'Kontaktieren Sie Uns'),
('contact.subtitle', 'en', 'We''d love to hear from you'),
('contact.subtitle', 'hr', 'Rado ćemo vas čuti'),
('contact.subtitle', 'it', 'Saremo lieti di sentirti'),
('contact.subtitle', 'de', 'Wir freuen uns von Ihnen zu hören'),
('contact.email', 'en', 'Email'),
('contact.email', 'hr', 'Email'),
('contact.email', 'it', 'Email'),
('contact.email', 'de', 'E-Mail'),
('contact.phone', 'en', 'Phone'),
('contact.phone', 'hr', 'Telefon'),
('contact.phone', 'it', 'Telefono'),
('contact.phone', 'de', 'Telefon'),
('contact.social', 'en', 'Follow Us'),
('contact.social', 'hr', 'Pratite Nas'),
('contact.social', 'it', 'Seguici'),
('contact.social', 'de', 'Folgen Sie Uns'),
('contact.copyright', 'en', '© 2025 Palazzina Burjaki. All rights reserved.'),
('contact.copyright', 'hr', '© 2025 Palazzina Burjaki. Sva prava pridržana.'),
('contact.copyright', 'it', '© 2025 Palazzina Burjaki. Tutti i diritti riservati.'),
('contact.copyright', 'de', '© 2025 Palazzina Burjaki. Alle Rechte vorbehalten.'),
('contact.privacy', 'en', 'Privacy Policy'),
('contact.privacy', 'hr', 'Politika Privatnosti'),
('contact.privacy', 'it', 'Privacy Policy'),
('contact.privacy', 'de', 'Datenschutz'),
('contact.terms', 'en', 'Terms of Service'),
('contact.terms', 'hr', 'Uvjeti Korištenja'),
('contact.terms', 'it', 'Termini di Servizio'),
('contact.terms', 'de', 'Nutzungsbedingungen'),
-- Footer
('footer.impressum', 'en', 'Legal Information'),
('footer.impressum', 'hr', 'Pravne informacije'),
('footer.impressum', 'it', 'Informazioni legali'),
('footer.impressum', 'de', 'Impressum'),
('footer.renterType', 'en', 'Private Rental'),
('footer.renterType', 'hr', 'Privatni iznajmljivač'),
('footer.renterType', 'it', 'Affitto privato'),
('footer.renterType', 'de', 'Private Vermietung'),
('footer.reservations', 'en', 'Reservations'),
('footer.reservations', 'hr', 'Rezervacije'),
('footer.reservations', 'it', 'Prenotazioni'),
('footer.reservations', 'de', 'Reservierungen'),
('footer.reservationsNotice', 'en', 'All reservations and payments are processed exclusively through the Airbnb platform.'),
('footer.reservationsNotice', 'hr', 'Sve rezervacije i plaćanja obavljaju se isključivo putem platforme Airbnb.'),
('footer.reservationsNotice', 'it', 'Tutte le prenotazioni e i pagamenti vengono elaborati esclusivamente attraverso la piattaforma Airbnb.'),
('footer.reservationsNotice', 'de', 'Alle Reservierungen und Zahlungen werden ausschließlich über die Airbnb-Plattform abgewickelt.'),
('footer.bookOnAirbnb', 'en', 'Book on Airbnb'),
('footer.bookOnAirbnb', 'hr', 'Rezerviraj na Airbnb'),
('footer.bookOnAirbnb', 'it', 'Prenota su Airbnb'),
('footer.bookOnAirbnb', 'de', 'Auf Airbnb buchen'),
('footer.noPaymentData', 'en', 'This website does not collect payment data or process reservations.'),
('footer.noPaymentData', 'hr', 'Ova web stranica ne prikuplja podatke o plaćanju niti obrađuje rezervacije.'),
('footer.noPaymentData', 'it', 'Questo sito web non raccoglie dati di pagamento né elabora prenotazioni.'),
('footer.noPaymentData', 'de', 'Diese Website erfasst keine Zahlungsdaten und verarbeitet keine Reservierungen.'),
('footer.legal', 'en', 'Legal'),
('footer.legal', 'hr', 'Pravno'),
('footer.legal', 'it', 'Legale'),
('footer.legal', 'de', 'Rechtliches'),
('footer.privacyPolicy', 'en', 'Privacy Policy'),
('footer.privacyPolicy', 'hr', 'Politika privatnosti'),
('footer.privacyPolicy', 'it', 'Informativa sulla privacy'),
('footer.privacyPolicy', 'de', 'Datenschutzerklärung'),
('footer.cookiePolicy', 'en', 'Cookie Policy'),
('footer.cookiePolicy', 'hr', 'Politika kolačića'),
('footer.cookiePolicy', 'it', 'Politica sui cookie'),
('footer.cookiePolicy', 'de', 'Cookie-Richtlinie'),
('footer.websiteNotice', 'en', 'Website Notice'),
('footer.websiteNotice', 'hr', 'Obavijest o stranici'),
('footer.websiteNotice', 'it', 'Avviso sul sito web'),
('footer.websiteNotice', 'de', 'Website-Hinweis'),
('footer.websiteNoticeText', 'en', 'This website is for informational purposes only. It provides details about Villa Palazzina Burjaki and redirects visitors to Airbnb for bookings.'),
('footer.websiteNoticeText', 'hr', 'Ova web stranica služi isključivo u informativne svrhe. Pruža informacije o Villa Palazzina Burjaki i preusmjerava posjetitelje na Airbnb za rezervacije.'),
('footer.websiteNoticeText', 'it', 'Questo sito web è solo a scopo informativo. Fornisce dettagli su Villa Palazzina Burjaki e reindirizza i visitatori su Airbnb per le prenotazioni.'),
('footer.websiteNoticeText', 'de', 'Diese Website dient ausschließlich Informationszwecken. Sie bietet Details über Villa Palazzina Burjaki und leitet Besucher für Buchungen zu Airbnb weiter.'),
('footer.allRightsReserved', 'en', 'All rights reserved.'),
('footer.allRightsReserved', 'hr', 'Sva prava pridržana.'),
('footer.allRightsReserved', 'it', 'Tutti i diritti riservati.'),
('footer.allRightsReserved', 'de', 'Alle Rechte vorbehalten.'),
('footer.legalDisclaimer', 'en', 'All reservations are made exclusively through the Airbnb platform. This website does not enable online payments or booking processing.'),
('footer.legalDisclaimer', 'hr', 'Sve rezervacije obavljaju se isključivo putem platforme Airbnb. Ova web stranica ne omogućuje online plaćanja niti obradu rezervacija.'),
('footer.legalDisclaimer', 'it', 'Tutte le prenotazioni vengono effettuate esclusivamente tramite la piattaforma Airbnb. Questo sito web non consente pagamenti online né elaborazione di prenotazioni.'),
('footer.legalDisclaimer', 'de', 'Alle Reservierungen erfolgen ausschließlich über die Airbnb-Plattform. Diese Website ermöglicht keine Online-Zahlungen oder Buchungsabwicklung.'),
-- Legal common
('legal.backToHome', 'en', 'Back to Home'),
('legal.backToHome', 'hr', 'Povratak na početnu'),
('legal.backToHome', 'it', 'Torna alla home'),
('legal.backToHome', 'de', 'Zurück zur Startseite'),
-- Cookie consent
('cookieConsent.message', 'en', 'This website uses essential cookies and third-party services to enhance your experience.'),
('cookieConsent.message', 'hr', 'Ova web stranica koristi osnovne kolačiće i usluge trećih strana kako bi poboljšala vaše iskustvo.'),
('cookieConsent.message', 'it', 'Questo sito web utilizza cookie essenziali e servizi di terze parti per migliorare la tua esperienza.'),
('cookieConsent.message', 'de', 'Diese Website verwendet essenzielle Cookies und Dienste von Drittanbietern, um Ihr Erlebnis zu verbessern.'),
('cookieConsent.learnMore', 'en', 'Learn more'),
('cookieConsent.learnMore', 'hr', 'Saznaj više'),
('cookieConsent.learnMore', 'it', 'Scopri di più'),
('cookieConsent.learnMore', 'de', 'Mehr erfahren'),
('cookieConsent.accept', 'en', 'Accept'),
('cookieConsent.accept', 'hr', 'Prihvati'),
('cookieConsent.accept', 'it', 'Accetta'),
('cookieConsent.accept', 'de', 'Akzeptieren');
