
INSERT INTO public.translations (key, lang, value) VALUES
-- Amenities
('amenities.label', 'en', 'Villa Features'),
('amenities.label', 'hr', 'Sadržaji Vile'),
('amenities.label', 'it', 'Caratteristiche Villa'),
('amenities.label', 'de', 'Villa Ausstattung'),
('amenities.title', 'en', 'Premium Amenities'),
('amenities.title', 'hr', 'Premium Sadržaji'),
('amenities.title', 'it', 'Servizi Premium'),
('amenities.title', 'de', 'Premium Ausstattung'),
('amenities.subtitle', 'en', 'Everything you need for an unforgettable stay'),
('amenities.subtitle', 'hr', 'Sve što vam je potrebno za nezaboravan boravak'),
('amenities.subtitle', 'it', 'Tutto ciò di cui hai bisogno per un soggiorno indimenticabile'),
('amenities.subtitle', 'de', 'Alles was Sie für einen unvergesslichen Aufenthalt brauchen'),
('amenities.pool.title', 'en', 'Private Pool'),
('amenities.pool.title', 'hr', 'Privatni Bazen'),
('amenities.pool.title', 'it', 'Piscina Privata'),
('amenities.pool.title', 'de', 'Privatpool'),
('amenities.pool.description', 'en', 'Seasonal outdoor pool'),
('amenities.pool.description', 'hr', 'Sezonski vanjski bazen'),
('amenities.pool.description', 'it', 'Piscina esterna stagionale'),
('amenities.pool.description', 'de', 'Saisonaler Außenpool'),
('amenities.wellness.title', 'en', 'Wellness Zone'),
('amenities.wellness.title', 'hr', 'Wellness Zona'),
('amenities.wellness.title', 'it', 'Zona Benessere'),
('amenities.wellness.title', 'de', 'Wellnessbereich'),
('amenities.wellness.description', 'en', 'Jacuzzi & sauna'),
('amenities.wellness.description', 'hr', 'Jacuzzi i sauna'),
('amenities.wellness.description', 'it', 'Jacuzzi e sauna'),
('amenities.wellness.description', 'de', 'Whirlpool & Sauna'),
('amenities.fitness.title', 'en', 'Fitness Center'),
('amenities.fitness.title', 'hr', 'Fitness Centar'),
('amenities.fitness.title', 'it', 'Centro Fitness'),
('amenities.fitness.title', 'de', 'Fitnesscenter'),
('amenities.fitness.description', 'en', 'Fully equipped gym'),
('amenities.fitness.description', 'hr', 'Potpuno opremljena teretana'),
('amenities.fitness.description', 'it', 'Palestra completamente attrezzata'),
('amenities.fitness.description', 'de', 'Voll ausgestattetes Fitnessstudio'),
('amenities.basketball.title', 'en', 'Basketball Court'),
('amenities.basketball.title', 'hr', 'Košarkaški Teren'),
('amenities.basketball.title', 'it', 'Campo da Basket'),
('amenities.basketball.title', 'de', 'Basketballplatz'),
('amenities.basketball.description', 'en', 'For active recreation'),
('amenities.basketball.description', 'hr', 'Za aktivnu rekreaciju'),
('amenities.basketball.description', 'it', 'Per la ricreazione attiva'),
('amenities.basketball.description', 'de', 'Für aktive Erholung'),
('amenities.wifi.title', 'en', 'Free WiFi'),
('amenities.wifi.title', 'hr', 'Besplatan WiFi'),
('amenities.wifi.title', 'it', 'WiFi Gratuito'),
('amenities.wifi.title', 'de', 'Kostenloses WLAN'),
('amenities.wifi.description', 'en', 'High-speed internet'),
('amenities.wifi.description', 'hr', 'Brzi internet'),
('amenities.wifi.description', 'it', 'Internet ad alta velocità'),
('amenities.wifi.description', 'de', 'Highspeed-Internet'),
('amenities.bbq.title', 'en', 'BBQ & Garden'),
('amenities.bbq.title', 'hr', 'Roštilj i Vrt'),
('amenities.bbq.title', 'it', 'BBQ e Giardino'),
('amenities.bbq.title', 'de', 'BBQ & Garten'),
('amenities.bbq.description', 'en', 'Terrace with garden furniture'),
('amenities.bbq.description', 'hr', 'Terasa s vrtnim namještajem'),
('amenities.bbq.description', 'it', 'Terrazza con mobili da giardino'),
('amenities.bbq.description', 'de', 'Terrasse mit Gartenmöbeln'),
('amenities.ac.title', 'en', 'Air Conditioning'),
('amenities.ac.title', 'hr', 'Klima Uređaj'),
('amenities.ac.title', 'it', 'Aria Condizionata'),
('amenities.ac.title', 'de', 'Klimaanlage'),
('amenities.ac.description', 'en', 'In all rooms'),
('amenities.ac.description', 'hr', 'U svim sobama'),
('amenities.ac.description', 'it', 'In tutte le stanze'),
('amenities.ac.description', 'de', 'In allen Zimmern'),
('amenities.entertainment.title', 'en', 'Entertainment'),
('amenities.entertainment.title', 'hr', 'Zabava'),
('amenities.entertainment.title', 'it', 'Intrattenimento'),
('amenities.entertainment.title', 'de', 'Unterhaltung'),
('amenities.entertainment.description', 'en', 'Satellite TV & PlayStation'),
('amenities.entertainment.description', 'hr', 'Satelitska TV i PlayStation'),
('amenities.entertainment.description', 'it', 'TV satellitare e PlayStation'),
('amenities.entertainment.description', 'de', 'Sat-TV & PlayStation'),
-- Location main
('location.label', 'en', 'Burjaki, Istria'),
('location.label', 'hr', 'Burjaki, Istra'),
('location.label', 'it', 'Burjaki, Istria'),
('location.label', 'de', 'Burjaki, Istrien'),
('location.title', 'en', 'Perfect Location'),
('location.title', 'hr', 'Savršena Lokacija'),
('location.title', 'it', 'Posizione Perfetta'),
('location.title', 'de', 'Perfekte Lage'),
('location.subtitle', 'en', 'Burjaki 36, Trgetari 52224, Croatia'),
('location.subtitle', 'hr', 'Burjaki 36, Trgetari 52224, Hrvatska'),
('location.subtitle', 'it', 'Burjaki 36, Trgetari 52224, Croazia'),
('location.subtitle', 'de', 'Burjaki 36, Trgetari 52224, Kroatien'),
-- Location categories
('location.category.beaches', 'en', 'Beaches'),
('location.category.beaches', 'hr', 'Plaže'),
('location.category.beaches', 'it', 'Spiagge'),
('location.category.beaches', 'de', 'Strände'),
('location.category.towns', 'en', 'Towns & Cities'),
('location.category.towns', 'hr', 'Gradovi'),
('location.category.towns', 'it', 'Città'),
('location.category.towns', 'de', 'Städte'),
('location.category.transport', 'en', 'Transport'),
('location.category.transport', 'hr', 'Prijevoz'),
('location.category.transport', 'it', 'Trasporti'),
('location.category.transport', 'de', 'Transport'),
('location.category.restaurants', 'en', 'Restaurants'),
('location.category.restaurants', 'hr', 'Restorani'),
('location.category.restaurants', 'it', 'Ristoranti'),
('location.category.restaurants', 'de', 'Restaurants'),
('location.category.supermarkets', 'en', 'Supermarkets'),
('location.category.supermarkets', 'hr', 'Supermarketi'),
('location.category.supermarkets', 'it', 'Supermercati'),
('location.category.supermarkets', 'de', 'Supermärkte'),
-- Beaches
('location.santaMarina.title', 'en', 'Sveta Marina Beach'),
('location.santaMarina.title', 'hr', 'Plaža Sveta Marina'),
('location.santaMarina.title', 'it', 'Spiaggia Sveta Marina'),
('location.santaMarina.title', 'de', 'Strand Sveta Marina'),
('location.santaMarina.distance', 'en', '16 km'),
('location.santaMarina.distance', 'hr', '16 km'),
('location.santaMarina.distance', 'it', '16 km'),
('location.santaMarina.distance', 'de', '16 km'),
('location.santaMarina.description', 'en', 'A hidden gem with stunning views and pristine waters. Perfect for a peaceful day of swimming and relaxation.'),
('location.santaMarina.description', 'hr', 'Skriveni dragulj sa zadivljujućim pogledom i čistim morem. Savršeno za miran dan kupanja i opuštanja.'),
('location.santaMarina.description', 'it', 'Un gioiello nascosto con viste mozzafiato e acque incontaminate. Perfetto per una giornata tranquilla di nuoto e relax.'),
('location.santaMarina.description', 'de', 'Ein verstecktes Juwel mit atemberaubender Aussicht und unberührtem Wasser. Perfekt für einen ruhigen Tag zum Schwimmen und Entspannen.'),
('location.tunarica.title', 'en', 'Tunarica Beach'),
('location.tunarica.title', 'hr', 'Plaža Tunarica'),
('location.tunarica.title', 'it', 'Spiaggia Tunarica'),
('location.tunarica.title', 'de', 'Strand Tunarica'),
('location.tunarica.distance', 'en', '11 km'),
('location.tunarica.distance', 'hr', '11 km'),
('location.tunarica.distance', 'it', '11 km'),
('location.tunarica.distance', 'de', '11 km'),
('location.tunarica.description', 'en', 'A secluded cove surrounded by lush greenery. Ideal for nature lovers seeking tranquility away from crowds.'),
('location.tunarica.description', 'hr', 'Osamljena uvala okružena bujnim zelenilom. Idealna za ljubitelje prirode koji traže mir daleko od gužvi.'),
('location.tunarica.description', 'it', 'Una baia appartata circondata da vegetazione rigogliosa. Ideale per gli amanti della natura in cerca di tranquillità.'),
('location.tunarica.description', 'de', 'Eine abgeschiedene Bucht umgeben von üppigem Grün. Ideal für Naturliebhaber auf der Suche nach Ruhe abseits der Massen.'),
('location.ravni.title', 'en', 'Trget Beach'),
('location.ravni.title', 'hr', 'Plaža Trget'),
('location.ravni.title', 'it', 'Spiaggia Trget'),
('location.ravni.title', 'de', 'Strand Trget'),
('location.ravni.distance', 'en', '2 km'),
('location.ravni.distance', 'hr', '2 km'),
('location.ravni.distance', 'it', '2 km'),
('location.ravni.distance', 'de', '2 km'),
('location.ravni.description', 'en', 'A peaceful pebble beach just minutes away — a true favorite among locals.'),
('location.ravni.description', 'hr', 'Mirna šljunčana plaža na samo nekoliko minuta vožnje — pravi favorit lokalaca.'),
('location.ravni.description', 'it', 'Una tranquilla spiaggia di ciottoli a pochi minuti di distanza — un vero favorito dei locali.'),
('location.ravni.description', 'de', 'Ein ruhiger Kiesstrand nur wenige Minuten entfernt — ein echter Favorit der Einheimischen.'),
('location.rabacBeaches.title', 'en', 'Rabac Beaches'),
('location.rabacBeaches.title', 'hr', 'Plaže Rabac'),
('location.rabacBeaches.title', 'it', 'Spiagge di Rabac'),
('location.rabacBeaches.title', 'de', 'Strände Rabac'),
('location.rabacBeaches.distance', 'en', '16 km'),
('location.rabacBeaches.distance', 'hr', '16 km'),
('location.rabacBeaches.distance', 'it', '16 km'),
('location.rabacBeaches.distance', 'de', '16 km'),
('location.rabacBeaches.description', 'en', 'Rabac offers award-winning beaches with turquoise waters and excellent facilities, earning its nickname "Pearl of Kvarner".'),
('location.rabacBeaches.description', 'hr', 'Rabac nudi nagrađivane plaže s tirkiznim morem i odličnim sadržajima, po čemu je i dobio nadimak "Biser Kvarnera".'),
('location.rabacBeaches.description', 'it', 'Rabac offre spiagge premiate con acque turchesi e strutture eccellenti, guadagnandosi il soprannome di "Perla del Quarnero".'),
('location.rabacBeaches.description', 'de', 'Rabac bietet preisgekrönte Strände mit türkisfarbenem Wasser und ausgezeichneten Einrichtungen, weshalb es "Perle des Kvarner" genannt wird.'),
-- Towns
('location.labin.title', 'en', 'Labin Old Town'),
('location.labin.title', 'hr', 'Stari grad Labin'),
('location.labin.title', 'it', 'Città vecchia di Albona'),
('location.labin.title', 'de', 'Altstadt Labin'),
('location.labin.distance', 'en', '11 km'),
('location.labin.distance', 'hr', '11 km'),
('location.labin.distance', 'it', '11 km'),
('location.labin.distance', 'de', '11 km'),
('location.labin.description', 'en', 'A charming medieval hilltop town with mining heritage, art galleries, and Adriatic views.'),
('location.labin.description', 'hr', 'Šarmantni srednjovjekovni gradić s rudarskom baštinom, galerijama i pogledom na Jadran.'),
('location.labin.description', 'it', 'Un affascinante borgo medievale con eredità mineraria, gallerie d''arte e vista sull''Adriatico.'),
('location.labin.description', 'de', 'Eine charmante mittelalterliche Hügelstadt mit Bergbauerbe, Kunstgalerien und Adriablick.'),
('location.rabac.title', 'en', 'Rabac'),
('location.rabac.title', 'hr', 'Rabac'),
('location.rabac.title', 'it', 'Rabac'),
('location.rabac.title', 'de', 'Rabac'),
('location.rabac.distance', 'en', '16 km'),
('location.rabac.distance', 'hr', '16 km'),
('location.rabac.distance', 'it', '16 km'),
('location.rabac.distance', 'de', '16 km'),
('location.rabac.description', 'en', 'A lively coastal resort with beautiful beaches, promenades, and excellent seafood restaurants.'),
('location.rabac.description', 'hr', 'Živahno obalno odmaralište s prekrasnim plažama, šetnicom i izvrsnim ribljem restoranima.'),
('location.rabac.description', 'it', 'Un vivace resort costiero con belle spiagge, lungomare e ottimi ristoranti di pesce.'),
('location.rabac.description', 'de', 'Ein lebhafter Küstenort mit schönen Stränden, Promenaden und ausgezeichneten Fischrestaurants.'),
('location.rovinj.title', 'en', 'Rovinj'),
('location.rovinj.title', 'hr', 'Rovinj'),
('location.rovinj.title', 'it', 'Rovigno'),
('location.rovinj.title', 'de', 'Rovinj'),
('location.rovinj.distance', 'en', '53 km'),
('location.rovinj.distance', 'hr', '53 km'),
('location.rovinj.distance', 'it', '53 km'),
('location.rovinj.distance', 'de', '53 km'),
('location.rovinj.description', 'en', 'Istria''s most romantic town with colorful houses, stone streets, and St. Euphemia Church.'),
('location.rovinj.description', 'hr', 'Najromantičniji grad Istre sa šarenim kućama, kamenim ulicama i crkvom Sv. Eufemije.'),
('location.rovinj.description', 'it', 'La città più romantica dell''Istria con case colorate, vie di pietra e la Chiesa di Santa Eufemia.'),
('location.rovinj.description', 'de', 'Istriens romantischste Stadt mit bunten Häusern, Steinstraßen und der Kirche der Hl. Euphemia.'),
('location.pula.title', 'en', 'Pula'),
('location.pula.title', 'hr', 'Pula'),
('location.pula.title', 'it', 'Pola'),
('location.pula.title', 'de', 'Pula'),
('location.pula.distance', 'en', '40 km'),
('location.pula.distance', 'hr', '40 km'),
('location.pula.distance', 'it', '40 km'),
('location.pula.distance', 'de', '40 km'),
('location.pula.description', 'en', 'Pula is home to the magnificent Roman Arena and offers rich culture, vibrant nightlife, and excellent cuisine.'),
('location.pula.description', 'hr', 'Pula je dom veličanstvene rimske Arene te nudi bogatu kulturu, živahan noćni život i izvrsnu gastronomiju.'),
('location.pula.description', 'it', 'Pola ospita la magnifica Arena Romana e offre ricca cultura, vivace vita notturna e cucina eccellente.'),
('location.pula.description', 'de', 'Pula beherbergt die großartige römische Arena und bietet reiche Kultur, lebhaftes Nachtleben und exzellente Küche.'),
('location.rasa.title', 'en', 'Raša'),
('location.rasa.title', 'hr', 'Raša'),
('location.rasa.title', 'it', 'Arsia'),
('location.rasa.title', 'de', 'Raša'),
('location.rasa.distance', 'en', '12 km'),
('location.rasa.distance', 'hr', '12 km'),
('location.rasa.distance', 'it', '12 km'),
('location.rasa.distance', 'de', '12 km'),
('location.rasa.description', 'en', 'Raša is the youngest town in Istria, featuring unique mining heritage and a peaceful atmosphere.'),
('location.rasa.description', 'hr', 'Raša je najmlađi grad u Istri, prepoznatljiv po jedinstvenoj rudarskoj baštini i mirnom okruženju.'),
('location.rasa.description', 'it', 'Arsia è la città più giovane dell''Istria, caratterizzata da un patrimonio minerario unico e un''atmosfera tranquilla.'),
('location.rasa.description', 'de', 'Raša ist die jüngste Stadt Istriens mit einzigartigem Bergbauerbe und einer friedlichen Atmosphäre.');
